/*
 * JS for startScreen generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return '9c845696-a97f-4685-9429-96badf635316';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "tests",
    "location": "#tests"
}, {
    "name": "startScreen_clone_1",
    "location": "#startScreen_clone_1"
}, {
    "name": "startScreen",
    "location": "#startScreen"
}];

startScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_90': 'startScreen_mobilebutton_90',
        'mobilebutton_92': 'startScreen_mobilebutton_92',
        'adhd_but_off': 'startScreen_adhd_but_off',
        'adhd_on': 'startScreen_adhd_on',
        'adhd': 'startScreen_adhd',
        'anti_but_off': 'startScreen_anti_but_off',
        'anti_but_on': 'startScreen_anti_but_on',
        'antidepressants': 'startScreen_antidepressants',
        'dep_but_off': 'startScreen_dep_but_off',
        'dep_but_on': 'startScreen_dep_but_on',
        'dep': 'startScreen_dep',
        'db_but_off': 'startScreen_db_but_off',
        'db_but_on': 'startScreen_db_but_on',
        'DB': 'startScreen_DB',
        'ed_but_off': 'startScreen_ed_but_off',
        'ed_but_on': 'startScreen_ed_but_on',
        'ed': 'startScreen_ed',
        'infant_but_off': 'startScreen_infant_but_off',
        'infant_but_on': 'startScreen_infant_but_on',
        'infant': 'startScreen_infant',
        'panic_but_off': 'startScreen_panic_but_off',
        'panic_but_on': 'startScreen_panic_but_on',
        'panic': 'startScreen_panic',
        'sleep_but_off': 'startScreen_sleep_but_off',
        'sleep_but_on': 'startScreen_sleep_but_on',
        'sleep': 'startScreen_sleep',
        'smoke_but_off': 'startScreen_smoke_but_off',
        'smoke_but_on': 'startScreen_smoke_but_on',
        'smoke': 'startScreen_smoke',
        'weight_but_off': 'startScreen_weight_but_off',
        'weight_but_on': 'startScreen_weight_but_on',
        'weight': 'startScreen_weight',
        'linkbutton_93': 'startScreen_linkbutton_93',
        'linkbutton_93_mobilebutton_31': 'startScreen_linkbutton_93_mobilebutton_31'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    restservice1 = new Appery.DataSource(WarehouseDB_merchandise_list_service, {
        'onComplete': function(jqXHR, textStatus) {

            Appery.refreshScreenFormElements("startScreen");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['X-Appery-Database-Id'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': '{database_id}'
        }]
    });

    datasources.push(restservice1);

    /*
     * Events and handlers
     */

    // Before Show
    var startScreen_beforeshow = function() {
            Appery.CurrentScreen = "startScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events
    var startScreen_windowEvents = function() {

            $('#startScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });
            $('#startScreen').on({
                pageshow: function() {
                    try {
                        restservice1.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                },
            });

        };

    // device events
    var startScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var startScreen_elementsExtraJS = function() {
            // screen (startScreen) extra code

            Appery.registerYoutubeComponent("startScreen_adhd");

            Appery.registerYoutubeComponent("startScreen_antidepressants");

            Appery.registerYoutubeComponent("startScreen_dep");

            Appery.registerYoutubeComponent("startScreen_DB");

            Appery.registerYoutubeComponent("startScreen_ed");

            Appery.registerYoutubeComponent("startScreen_infant");

            Appery.registerYoutubeComponent("startScreen_panic");

            Appery.registerYoutubeComponent("startScreen_sleep");

            Appery.registerYoutubeComponent("startScreen_smoke");

            Appery.registerYoutubeComponent("startScreen_weight");

        };

    // screen elements handler
    var startScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#startScreen_mobileheader1 [name="mobilebutton_90"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('startScreen_clone_1', {
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobileheader1 [name="mobilebutton_90"]');
            $(document).off("click", '#startScreen_mobileheader1 [name="mobilebutton_92"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('tests', {
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobileheader1 [name="mobilebutton_92"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="adhd_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_adhd', 'mob', 'true');
                        toggle('startScreen_adhd_but_off', 'mob', 'false');
                        toggle('startScreen_adhd_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="adhd_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="adhd_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_adhd_on', 'mob', 'false');
                        toggle('startScreen_adhd', 'mob', 'false');
                        toggle('startScreen_adhd_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="adhd_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="anti_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_antidepressants', 'mob', 'true');
                        toggle('startScreen_anti_but_on', 'mob', 'true');
                        toggle('startScreen_anti_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="anti_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="anti_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_antidepressants', 'mob', 'false');
                        toggle('startScreen_anti_but_on', 'mob', 'false');
                        toggle('startScreen_anti_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="anti_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="dep_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_dep', 'mob', 'true');
                        toggle('startScreen_dep_but_off', 'mob', 'false');
                        toggle('startScreen_dep_but_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="dep_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="dep_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_dep', 'mob', 'false');
                        toggle('startScreen_dep_but_on', 'mob', 'false');
                        toggle('startScreen_dep_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="dep_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="db_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_DB', 'mob', 'true');
                        toggle('startScreen_db_but_on', 'mob', 'true');
                        toggle('startScreen_db_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="db_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="db_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_db_but_on', 'mob', 'false');
                        toggle('startScreen_DB', 'mob', 'false');
                        toggle('startScreen_db_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="db_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="ed_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_ed', 'mob', 'true');
                        toggle('startScreen_ed_but_on', 'mob', 'true');
                        toggle('startScreen_ed_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="ed_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="ed_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_ed', 'mob', 'false');
                        toggle('startScreen_ed_but_on', 'mob', 'false');
                        toggle('startScreen_ed_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="ed_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="infant_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_infant', 'mob', 'true');
                        toggle('startScreen_infant_but_on', 'mob', 'true');
                        toggle('startScreen_infant_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="infant_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="infant_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_infant_but_off', 'mob', 'true');
                        toggle('startScreen_infant', 'mob', 'false');
                        toggle('startScreen_infant_but_on', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="infant_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="panic_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_panic', 'mob', 'true');
                        toggle('startScreen_panic_but_on', 'mob', 'true');
                        toggle('startScreen_panic_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="panic_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="panic_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_panic', 'mob', 'false');
                        toggle('startScreen_panic_but_off', 'mob', 'true');
                        toggle('startScreen_panic_but_on', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="panic_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="sleep_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_sleep', 'mob', 'true');
                        toggle('startScreen_sleep_but_on', 'mob', 'true');
                        toggle('startScreen_sleep_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="sleep_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="sleep_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_sleep', 'mob', 'false');
                        toggle('startScreen_sleep_but_off', 'mob', 'true');
                        toggle('startScreen_sleep_but_on', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="sleep_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="smoke_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_smoke', 'mob', 'true');
                        toggle('startScreen_smoke_but_on', 'mob', 'true');
                        toggle('startScreen_smoke_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="smoke_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="smoke_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_smoke', 'mob', 'false');
                        toggle('startScreen_smoke_but_on', 'mob', 'false');
                        toggle('startScreen_smoke_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="smoke_but_on"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="weight_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_weight', 'mob', 'true');
                        toggle('startScreen_weight_but_on', 'mob', 'true');
                        toggle('startScreen_weight_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="weight_but_off"]');
            $(document).off("click", '#startScreen_mobilecontainer1 [name="weight_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_weight', 'mob', 'false');
                        toggle('startScreen_weight_but_on', 'mob', 'false');
                        toggle('startScreen_weight_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="weight_but_on"]');

            $(document).off("click", '#startScreen_mobilefooter1 [name="linkbutton_93_mobilebutton_31"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        window.open('http://www.primarycareshrink.com', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                    }
                },
            }, '#startScreen_mobilefooter1 [name="linkbutton_93_mobilebutton_31"]');

        };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Appery.processSelectMenu($(this));
    startScreen_js();
});

tests_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'videos': 'tests_videos',
        'reset': 'tests_reset',
        'phq_off': 'tests_phq_off',
        'phq_on': 'tests_phq_on',
        'q1': 'tests_q1',
        'phq1': 'tests_phq1',
        'phq1-0': 'tests_phq1-0',
        'q2': 'tests_q2',
        'phq2': 'tests_phq2',
        'phq2-0': 'tests_phq2-0',
        'q3': 'tests_q3',
        'phq3': 'tests_phq3',
        'phq3-0': 'tests_phq3-0',
        'q4': 'tests_q4',
        'phq4': 'tests_phq4',
        'phq4-0': 'tests_phq4-0',
        'q5': 'tests_q5',
        'phq5': 'tests_phq5',
        'phq5-0': 'tests_phq5-0',
        'q6': 'tests_q6',
        'phq6': 'tests_phq6',
        'phq6-0': 'tests_phq6-0',
        'q7': 'tests_q7',
        'phq7': 'tests_phq7',
        'phq7-0': 'tests_phq7-0',
        'q8': 'tests_q8',
        'phq8': 'tests_phq8',
        'phq8-0': 'tests_phq8-0',
        'q9': 'tests_q9',
        'phq9': 'tests_phq9',
        'phq9-0': 'tests_phq9-0',
        'phq_score': 'tests_phq_score',
        'phqrange': 'tests_phqrange',
        'phq_sp_off': 'tests_phq_sp_off',
        'phq_sp_on': 'tests_phq_sp_on',
        'sp_q1': 'tests_sp_q1',
        'sp_phq1': 'tests_sp_phq1',
        'sp_phq1-0': 'tests_sp_phq1-0',
        'sp_q2': 'tests_sp_q2',
        'sp_phq2': 'tests_sp_phq2',
        'sp_phq2-0': 'tests_sp_phq2-0',
        'sp_q3': 'tests_sp_q3',
        'sp_phq3': 'tests_sp_phq3',
        'sp_phq3-0': 'tests_sp_phq3-0',
        'sp_q4': 'tests_sp_q4',
        'sp_phq4': 'tests_sp_phq4',
        'sp_phq4-0': 'tests_sp_phq4-0',
        'sp_q5': 'tests_sp_q5',
        'sp_phq5': 'tests_sp_phq5',
        'sp_phq5-0': 'tests_sp_phq5-0',
        'sp_q6': 'tests_sp_q6',
        'sp_phq6': 'tests_sp_phq6',
        'sp_phq6-0': 'tests_sp_phq6-0',
        'sp_q7': 'tests_sp_q7',
        'sp_phq7': 'tests_sp_phq7',
        'sp_phq7-0': 'tests_sp_phq7-0',
        'sp_q8': 'tests_sp_q8',
        'sp_phq8': 'tests_sp_phq8',
        'sp_phq8-0': 'tests_sp_phq8-0',
        'sp_q9': 'tests_sp_q9',
        'sp_phq9': 'tests_sp_phq9',
        'sp_phq9-0': 'tests_sp_phq9-0',
        'sp_phqscore': 'tests_sp_phqscore',
        'sp_phqrange': 'tests_sp_phqrange',
        'gad_off': 'tests_gad_off',
        'gad_on': 'tests_gad_on',
        'g1': 'tests_g1',
        'gad1': 'tests_gad1',
        'gad1-0': 'tests_gad1-0',
        'g2': 'tests_g2',
        'gad2': 'tests_gad2',
        'gad2-0': 'tests_gad2-0',
        'g3': 'tests_g3',
        'gad3': 'tests_gad3',
        'gad3-0': 'tests_gad3-0',
        'g4': 'tests_g4',
        'gad4': 'tests_gad4',
        'gad4-0': 'tests_gad4-0',
        'g5': 'tests_g5',
        'gad5': 'tests_gad5',
        'gad5-0': 'tests_gad5-0',
        'g6': 'tests_g6',
        'gad6': 'tests_gad6',
        'gad6-0': 'tests_gad6-0',
        'g7': 'tests_g7',
        'gad7': 'tests_gad7',
        'gad7-0': 'tests_gad7-0',
        'gad7score': 'tests_gad7score',
        'gadrange': 'tests_gadrange',
        'gad7_sp_off': 'tests_gad7_sp_off',
        'gady7_sp_on': 'tests_gady7_sp_on',
        'spg1': 'tests_spg1',
        'spgad1': 'tests_spgad1',
        'spgad1-0': 'tests_spgad1-0',
        'spg2': 'tests_spg2',
        'spgad2': 'tests_spgad2',
        'spgad2-0': 'tests_spgad2-0',
        'spg3': 'tests_spg3',
        'spgad3': 'tests_spgad3',
        'spgad3-0': 'tests_spgad3-0',
        'spg4': 'tests_spg4',
        'spgad4': 'tests_spgad4',
        'spgad4-0': 'tests_spgad4-0',
        'spg5': 'tests_spg5',
        'spgad5': 'tests_spgad5',
        'spgad5-0': 'tests_spgad5-0',
        'spg6': 'tests_spg6',
        'spgad6': 'tests_spgad6',
        'spgad6-0': 'tests_spgad6-0',
        'spg7': 'tests_spg7',
        'spgad7': 'tests_spgad7',
        'spgad7-0': 'tests_spgad7-0',
        'spgadscore': 'tests_spgadscore',
        'spgadrange': 'tests_spgadrange',
        'linkbutton_41': 'tests_linkbutton_41',
        'linkbutton_41_mobilebutton_31': 'tests_linkbutton_41_mobilebutton_31'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'tests';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var tests_beforeshow = function() {
            Appery.CurrentScreen = "tests";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var tests_onLoad = function() {
            tests_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            tests_deviceEvents();
            tests_windowEvents();
            tests_elementsEvents();
        };

    // screen window events
    var tests_windowEvents = function() {

            $('#tests').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var tests_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var tests_elementsExtraJS = function() {
            // screen (tests) extra code

            /* phq1 */

            $("#tests_phq1").parent().find("a.ui-btn").attr("tabindex", "9");

            /* phq2 */

            $("#tests_phq2").parent().find("a.ui-btn").attr("tabindex", "12");

            /* phq3 */

            $("#tests_phq3").parent().find("a.ui-btn").attr("tabindex", "13");

            /* phq4 */

            $("#tests_phq4").parent().find("a.ui-btn").attr("tabindex", "14");

            /* phq5 */

            $("#tests_phq5").parent().find("a.ui-btn").attr("tabindex", "15");

            /* phq6 */

            $("#tests_phq6").parent().find("a.ui-btn").attr("tabindex", "16");

            /* phq7 */

            $("#tests_phq7").parent().find("a.ui-btn").attr("tabindex", "17");

            /* phq8 */

            $("#tests_phq8").parent().find("a.ui-btn").attr("tabindex", "18");

            /* phq9 */

            $("#tests_phq9").parent().find("a.ui-btn").attr("tabindex", "19");

            /* sp_phq1 */

            $("#tests_sp_phq1").parent().find("a.ui-btn").attr("tabindex", "23");

            /* sp_phq2 */

            $("#tests_sp_phq2").parent().find("a.ui-btn").attr("tabindex", "25");

            /* sp_phq3 */

            $("#tests_sp_phq3").parent().find("a.ui-btn").attr("tabindex", "27");

            /* sp_phq4 */

            $("#tests_sp_phq4").parent().find("a.ui-btn").attr("tabindex", "28");

            /* sp_phq5 */

            $("#tests_sp_phq5").parent().find("a.ui-btn").attr("tabindex", "29");

            /* sp_phq6 */

            $("#tests_sp_phq6").parent().find("a.ui-btn").attr("tabindex", "30");

            /* sp_phq7 */

            $("#tests_sp_phq7").parent().find("a.ui-btn").attr("tabindex", "31");

            /* sp_phq8 */

            $("#tests_sp_phq8").parent().find("a.ui-btn").attr("tabindex", "32");

            /* sp_phq9 */

            $("#tests_sp_phq9").parent().find("a.ui-btn").attr("tabindex", "33");

            /* gad1 */

            $("#tests_gad1").parent().find("a.ui-btn").attr("tabindex", "36");

            /* gad2 */

            $("#tests_gad2").parent().find("a.ui-btn").attr("tabindex", "37");

            /* gad3 */

            $("#tests_gad3").parent().find("a.ui-btn").attr("tabindex", "38");

            /* gad4 */

            $("#tests_gad4").parent().find("a.ui-btn").attr("tabindex", "39");

            /* gad5 */

            $("#tests_gad5").parent().find("a.ui-btn").attr("tabindex", "40");

            /* gad6 */

            $("#tests_gad6").parent().find("a.ui-btn").attr("tabindex", "41");

            /* gad7 */

            $("#tests_gad7").parent().find("a.ui-btn").attr("tabindex", "42");

            /* spgad1 */

            $("#tests_spgad1").parent().find("a.ui-btn").attr("tabindex", "46");

            /* spgad2 */

            $("#tests_spgad2").parent().find("a.ui-btn").attr("tabindex", "49");

            /* spgad3 */

            $("#tests_spgad3").parent().find("a.ui-btn").attr("tabindex", "50");

            /* spgad4 */

            $("#tests_spgad4").parent().find("a.ui-btn").attr("tabindex", "51");

            /* spgad5 */

            $("#tests_spgad5").parent().find("a.ui-btn").attr("tabindex", "52");

            /* spgad6 */

            $("#tests_spgad6").parent().find("a.ui-btn").attr("tabindex", "56");

            /* spgad7 */

            $("#tests_spgad7").parent().find("a.ui-btn").attr("tabindex", "54");

        };

    // screen elements handler
    var tests_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#tests_mobileheader [name="videos"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('startScreen', {
                            reverse: false
                        });

                    }
                },
            }, '#tests_mobileheader [name="videos"]');
            $(document).off("click", '#tests_mobileheader [name="reset"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        setText('tests_phqrange', '');
                        setText('tests_gadrange', '');
                        setText('tests_sp_phqrange', '');
                        setText('tests_spgadrange', '');

                    }
                },
            }, '#tests_mobileheader [name="reset"]');

            $(document).off("click", '#tests_mobilecontainer [name="phq_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_phq_on', 'mob', 'true');
                        toggle('tests_phq_score', 'mob', 'true');
                        toggle('tests_q1', 'mob', 'true');
                        toggle('tests_q3', 'mob', 'true');
                        toggle('tests_q8', 'mob', 'true');
                        toggle('tests_q7', 'mob', 'true');
                        toggle('tests_q6', 'mob', 'true');
                        toggle('tests_q4', 'mob', 'true');
                        toggle('tests_phq_off', 'mob', 'false');
                        toggle('tests_phqrange', 'mob', 'true');
                        toggle('tests_q5', 'mob', 'true');
                        toggle('tests_q9', 'mob', 'true');
                        toggle('tests_q2', 'mob', 'true');
                        toggle('tests_phq1', 'mob', 'true');
                        toggle('tests_phq2', 'mob', 'true');
                        toggle('tests_phq_on', 'mob', 'true');
                        toggle('tests_phq3', 'mob', 'true');
                        toggle('tests_phq4', 'mob', 'true');
                        toggle('tests_phq5', 'mob', 'true');
                        toggle('tests_phq6', 'mob', 'true');
                        toggle('tests_phq7', 'mob', 'true');
                        toggle('tests_phq8', 'mob', 'true');
                        toggle('tests_phq9', 'mob', 'true');

                    }
                },
            }, '#tests_mobilecontainer [name="phq_off"]');
            $(document).off("click", '#tests_mobilecontainer [name="phq_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_phq_off', 'mob', 'true');
                        toggle('tests_phq1', 'mob', 'false');
                        toggle('tests_phq_on', 'mob', 'false');
                        toggle('tests_phq2', 'mob', 'false');
                        toggle('tests_phq_score', 'mob', 'false');
                        toggle('tests_q1', 'mob', 'false');
                        toggle('tests_phq3', 'mob', 'false');
                        toggle('tests_phq4', 'mob', 'false');
                        toggle('tests_phq5', 'mob', 'false');
                        toggle('tests_phq6', 'mob', 'false');
                        toggle('tests_phq7', 'mob', 'false');
                        toggle('tests_phq8', 'mob', 'false');
                        toggle('tests_phq9', 'mob', 'false');
                        toggle('tests_q1', 'mob', 'false');
                        toggle('tests_q2', 'mob', 'false');
                        toggle('tests_q3', 'mob', 'false');
                        toggle('tests_q4', 'mob', 'false');
                        toggle('tests_q5', 'mob', 'false');
                        toggle('tests_q6', 'mob', 'false');
                        toggle('tests_q7', 'mob', 'false');
                        toggle('tests_q8', 'mob', 'false');
                        toggle('tests_q9', 'mob', 'false');

                    }
                },
            }, '#tests_mobilecontainer [name="phq_on"]');

            $(document).off("click", '#tests_mobilecontainer [name="phq_score"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        var n1 = parseInt(Appery("phq1").val()),
                            n2 = parseInt(Appery("phq2").val()),
                            n3 = parseInt(Appery("phq3").val()),
                            n4 = parseInt(Appery("phq4").val()),
                            n5 = parseInt(Appery("phq5").val()),
                            n6 = parseInt(Appery("phq6").val()),
                            n7 = parseInt(Appery("phq7").val()),
                            n8 = parseInt(Appery("phq8").val()),
                            n9 = parseInt(Appery("phq9").val()),
                            totalnum = (n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9);

                        if (totalnum > 19) {
                            phqrange = "severe";
                        } else if (totalnum > 14) {
                            phqrange = "moderate severe";
                        } else if (totalnum > 9) {
                            phqrange = "moderate ";
                        } else if (totalnum > 4) {
                            phqrange = "mild";
                        } else {
                            phqrange = "normal";
                        }

                        var str1 = " PHQ Score: ";
                        var str2 = " Range: ";

                        var res = str1.concat(totalnum, str2, phqrange);

                        //Appery("totalnum").text(totalnum);
                        Appery("phqrange").text(res);

                        ;

                    }
                },
            }, '#tests_mobilecontainer [name="phq_score"]');

            $(document).off("click", '#tests_mobilecontainer [name="phq_sp_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_sp_phq1', 'mob', 'true');
                        toggle('tests_sp_phq2', 'mob', 'true');
                        toggle('tests_sp_phq3', 'mob', 'true');
                        toggle('tests_sp_phq4', 'mob', 'true');
                        toggle('tests_sp_phq5', 'mob', 'true');
                        toggle('tests_sp_phq6', 'mob', 'true');
                        toggle('tests_sp_phq7', 'mob', 'true');
                        toggle('tests_sp_phq9', 'mob', 'true');
                        toggle('tests_sp_q5', 'mob', 'true');
                        toggle('tests_sp_q6', 'mob', 'true');
                        toggle('tests_sp_q7', 'mob', 'true');
                        toggle('tests_sp_q8', 'mob', 'true');
                        toggle('tests_sp_q9', 'mob', 'true');
                        toggle('tests_sp_q1', 'mob', 'true');
                        toggle('tests_sp_q2', 'mob', 'true');
                        toggle('tests_sp_q3', 'mob', 'true');
                        toggle('tests_sp_q4', 'mob', 'true');
                        toggle('tests_sp_phqscore', 'mob', 'true');
                        toggle('tests_phq_sp_off', 'mob', 'false');
                        toggle('tests_phq_sp_on', 'mob', 'true');
                        toggle('tests_sp_phq8', 'mob', 'true');

                    }
                },
            }, '#tests_mobilecontainer [name="phq_sp_off"]');
            $(document).off("click", '#tests_mobilecontainer [name="phq_sp_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_phq_sp_off', 'mob', 'true');
                        toggle('tests_phq_sp_on', 'mob', 'false');
                        toggle('tests_sp_phq1', 'mob', 'false');
                        toggle('tests_sp_phq2', 'mob', 'false');
                        toggle('tests_sp_phq3', 'mob', 'false');
                        toggle('tests_sp_phq4', 'mob', 'false');
                        toggle('tests_sp_phq5', 'mob', 'false');
                        toggle('tests_sp_phq6', 'mob', 'false');
                        toggle('tests_sp_phq7', 'mob', 'false');
                        toggle('tests_sp_phq8', 'mob', 'false');
                        toggle('tests_sp_phq9', 'mob', 'false');
                        toggle('tests_sp_q1', 'mob', 'false');
                        toggle('tests_sp_q2', 'mob', 'false');
                        toggle('tests_sp_q3', 'mob', 'false');
                        toggle('tests_sp_q4', 'mob', 'false');
                        toggle('tests_sp_q5', 'mob', 'false');
                        toggle('tests_sp_q6', 'mob', 'false');
                        toggle('tests_sp_q7', 'mob', 'false');
                        toggle('tests_sp_q8', 'mob', 'false');
                        toggle('tests_sp_q9', 'mob', 'false');
                        toggle('tests_sp_phqscore', 'mob', 'false');

                    }
                },
            }, '#tests_mobilecontainer [name="phq_sp_on"]');

            $(document).off("click", '#tests_mobilecontainer [name="sp_phqscore"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        var n1 = parseInt(Appery("sp_phq1").val()),
                            n2 = parseInt(Appery("sp_phq2").val()),
                            n3 = parseInt(Appery("sp_phq3").val()),
                            n4 = parseInt(Appery("sp_phq4").val()),
                            n5 = parseInt(Appery("sp_phq5").val()),
                            n6 = parseInt(Appery("sp_phq6").val()),
                            n7 = parseInt(Appery("sp_phq7").val()),
                            n8 = parseInt(Appery("sp_phq8").val()),
                            n9 = parseInt(Appery("sp_phq9").val()),
                            totalnum = (n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9);

                        if (totalnum > 19) {
                            phqrange = "severe";
                        } else if (totalnum > 14) {
                            phqrange = "moderate severe";
                        } else if (totalnum > 9) {
                            phqrange = "moderate ";
                        } else if (totalnum > 4) {
                            phqrange = "mild";
                        } else {
                            phqrange = "normal";
                        }

                        var str1 = "PHQ Spanish Score: ";
                        var str2 = " Range: ";

                        var res = str1.concat(totalnum, str2, phqrange);

                        //Appery("totalnum").text(totalnum);
                        Appery("sp_phqrange").text(res);

                        ;

                    }
                },
            }, '#tests_mobilecontainer [name="sp_phqscore"]');

            $(document).off("click", '#tests_mobilecontainer [name="gad_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_g1', 'mob', 'true');
                        toggle('tests_g2', 'mob', 'true');
                        toggle('tests_g3', 'mob', 'true');
                        toggle('tests_g4', 'mob', 'true');
                        toggle('tests_g5', 'mob', 'true');
                        toggle('tests_g6', 'mob', 'true');
                        toggle('tests_g7', 'mob', 'true');
                        toggle('tests_gad_off', 'mob', 'false');
                        toggle('tests_gad_on', 'mob', 'true');
                        toggle('tests_gad1', 'mob', 'true');
                        toggle('tests_gad2', 'mob', 'true');
                        toggle('tests_gad3', 'mob', 'true');
                        toggle('tests_gad4', 'mob', 'true');
                        toggle('tests_gad5', 'mob', 'true');
                        toggle('tests_gad6', 'mob', 'true');
                        toggle('tests_gad7', 'mob', 'true');
                        toggle('tests_gad7score', 'mob', 'true');

                    }
                },
            }, '#tests_mobilecontainer [name="gad_off"]');
            $(document).off("click", '#tests_mobilecontainer [name="gad_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_g1', 'mob', 'false');
                        toggle('tests_g2', 'mob', 'false');
                        toggle('tests_g3', 'mob', 'false');
                        toggle('tests_g4', 'mob', 'false');
                        toggle('tests_g5', 'mob', 'false');
                        toggle('tests_g6', 'mob', 'false');
                        toggle('tests_g7', 'mob', 'false');
                        toggle('tests_gad1', 'mob', 'false');
                        toggle('tests_gad2', 'mob', 'false');
                        toggle('tests_gad3', 'mob', 'false');
                        toggle('tests_gad4', 'mob', 'false');
                        toggle('tests_gad5', 'mob', 'false');
                        toggle('tests_gad6', 'mob', 'false');
                        toggle('tests_gad7', 'mob', 'false');
                        toggle('tests_gad_off', 'mob', 'true');
                        toggle('tests_gad_on', 'mob', 'false');
                        toggle('tests_gad7score', 'mob', 'false');

                    }
                },
            }, '#tests_mobilecontainer [name="gad_on"]');

            $(document).off("click", '#tests_mobilecontainer [name="gad7score"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        var n1 = parseInt(Appery("gad1").val()),
                            n2 = parseInt(Appery("gad2").val()),
                            n3 = parseInt(Appery("gad3").val()),
                            n4 = parseInt(Appery("gad4").val()),
                            n5 = parseInt(Appery("gad5").val()),
                            n6 = parseInt(Appery("gad6").val()),
                            n7 = parseInt(Appery("gad7").val()),
                            totalnum = (n1 + n2 + n3 + n4 + n5 + n6 + n7);

                        if (totalnum > 14) {
                            gadrange = " severe";
                        } else if (totalnum > 9) {
                            gadrange = "moderate ";
                        } else if (totalnum > 4) {
                            gadrange = "mild";
                        } else {
                            gadrange = "normal";
                        }

                        var str1 = "GAD Score: ";
                        var str2 = " Range: ";

                        var res = str1.concat(totalnum, str2, gadrange);

                        //Appery("totalnum").text(totalnum);
                        Appery("gadrange").text(res);

                        ;

                    }
                },
            }, '#tests_mobilecontainer [name="gad7score"]');

            $(document).off("click", '#tests_mobilecontainer [name="gad7_sp_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_gad7_sp_off', 'mob', 'false');
                        toggle('tests_gady7_sp_on', 'mob', 'true');
                        toggle('tests_spgad1', 'mob', 'true');
                        toggle('tests_spg1', 'mob', 'true');
                        toggle('tests_spg2', 'mob', 'true');
                        toggle('tests_spg3', 'mob', 'true');
                        toggle('tests_spg4', 'mob', 'true');
                        toggle('tests_spg5', 'mob', 'true');
                        toggle('tests_spg6', 'mob', 'true');
                        toggle('tests_spg7', 'mob', 'true');
                        toggle('tests_spgad1', 'mob', 'true');
                        toggle('tests_spgad2', 'mob', 'true');
                        toggle('tests_spgad3', 'mob', 'true');
                        toggle('tests_spgad4', 'mob', 'true');
                        toggle('tests_spgad5', 'mob', 'true');
                        toggle('tests_spgad6', 'mob', 'true');
                        toggle('tests_spgad7', 'mob', 'true');
                        toggle('tests_spgadscore', 'mob', 'true');

                    }
                },
            }, '#tests_mobilecontainer [name="gad7_sp_off"]');
            $(document).off("click", '#tests_mobilecontainer [name="gady7_sp_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('tests_gad7_sp_off', 'mob', 'true');
                        toggle('tests_gady7_sp_on', 'mob', 'false');
                        toggle('tests_spg1', 'mob', 'false');
                        toggle('tests_spg2', 'mob', 'false');
                        toggle('tests_spg3', 'mob', 'false');
                        toggle('tests_spg4', 'mob', 'false');
                        toggle('tests_spg5', 'mob', 'false');
                        toggle('tests_spg6', 'mob', 'false');
                        toggle('tests_spg7', 'mob', 'false');
                        toggle('tests_spgad1', 'mob', 'false');
                        toggle('tests_spgad2', 'mob', 'false');
                        toggle('tests_spgad4', 'mob', 'false');
                        toggle('tests_spgad5', 'mob', 'false');
                        toggle('tests_spgad3', 'mob', 'false');
                        toggle('tests_spgad6', 'mob', 'false');
                        toggle('tests_spgad7', 'mob', 'false');
                        toggle('tests_spgadscore', 'mob', 'false');

                    }
                },
            }, '#tests_mobilecontainer [name="gady7_sp_on"]');

            $(document).off("click", '#tests_mobilecontainer [name="spgadscore"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        var n1 = parseInt(Appery("spgad1").val()),
                            n2 = parseInt(Appery("spgad2").val()),
                            n3 = parseInt(Appery("spgad3").val()),
                            n4 = parseInt(Appery("spgad4").val()),
                            n5 = parseInt(Appery("spgad5").val()),
                            n6 = parseInt(Appery("spgad6").val()),
                            n7 = parseInt(Appery("spgad7").val()),
                            totalnum = (n1 + n2 + n3 + n4 + n5 + n6 + n7);

                        if (totalnum > 14) {
                            gadrange = " severe";
                        } else if (totalnum > 9) {
                            gadrange = "moderate ";
                        } else if (totalnum > 4) {
                            gadrange = "mild";
                        } else {
                            gadrange = "normal";
                        }

                        var str1 = "GAD Spanish Score: ";
                        var str2 = " Range: ";

                        var res = str1.concat(totalnum, str2, gadrange);

                        //Appery("totalnum").text(totalnum);
                        Appery("spgadrange").text(res);

                        ;

                    }
                },
            }, '#tests_mobilecontainer [name="spgadscore"]');

            $(document).off("click", '#tests_mobilefooter [name="linkbutton_41_mobilebutton_31"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        window.open('http://www.primarycareshrink.com', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                    }
                },
            }, '#tests_mobilefooter [name="linkbutton_41_mobilebutton_31"]');

        };

    $(document).off("pagebeforeshow", "#tests").on("pagebeforeshow", "#tests", function(event, ui) {
        tests_beforeshow();
    });

    if (runBeforeShow) {
        tests_beforeshow();
    } else {
        tests_onLoad();
    }
};

$(document).off("pagecreate", "#tests").on("pagecreate", "#tests", function(event, ui) {
    Appery.processSelectMenu($(this));
    tests_js();
});

startScreen_clone_1_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_89': 'startScreen_clone_1_mobilebutton_89',
        'mobilebutton_90': 'startScreen_clone_1_mobilebutton_90',
        'adhd_sp_but_off': 'startScreen_clone_1_adhd_sp_but_off',
        'adhd_sp_but_on': 'startScreen_clone_1_adhd_sp_but_on',
        'adhd_spanish': 'startScreen_clone_1_adhd_spanish',
        'anti_sp_but_off': 'startScreen_clone_1_anti_sp_but_off',
        'anti_sp_but_on': 'startScreen_clone_1_anti_sp_but_on',
        'antidepressants_sp': 'startScreen_clone_1_antidepressants_sp',
        'dep_sp_but_off': 'startScreen_clone_1_dep_sp_but_off',
        'dep_sp_but_on': 'startScreen_clone_1_dep_sp_but_on',
        'dep_sp': 'startScreen_clone_1_dep_sp',
        'db_sp_off': 'startScreen_clone_1_db_sp_off',
        'db_sp_on': 'startScreen_clone_1_db_sp_on',
        'DB_sp': 'startScreen_clone_1_DB_sp',
        'ed_sp_but_off': 'startScreen_clone_1_ed_sp_but_off',
        'ed_sp_but_on': 'startScreen_clone_1_ed_sp_but_on',
        'ED_sp': 'startScreen_clone_1_ED_sp',
        'infant_but_off': 'startScreen_clone_1_infant_but_off',
        'infant_but_on': 'startScreen_clone_1_infant_but_on',
        'infant': 'startScreen_clone_1_infant',
        'panic_but_off': 'startScreen_clone_1_panic_but_off',
        'panic_but_on': 'startScreen_clone_1_panic_but_on',
        'panic': 'startScreen_clone_1_panic',
        'sleep_but_off': 'startScreen_clone_1_sleep_but_off',
        'sleep_but_on': 'startScreen_clone_1_sleep_but_on',
        'sleep_sp': 'startScreen_clone_1_sleep_sp',
        'weight_but_off': 'startScreen_clone_1_weight_but_off',
        'weight_but_on': 'startScreen_clone_1_weight_but_on',
        'weight': 'startScreen_clone_1_weight',
        'mobilebutton_31': 'startScreen_clone_1_mobilebutton_31'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'startScreen_clone_1';

    /*
     * Nonvisual components
     */
    var datasources = [];

    restservice1_clone_1 = new Appery.DataSource(WarehouseDB_merchandise_list_service, {
        'onComplete': function(jqXHR, textStatus) {

            Appery.refreshScreenFormElements("startScreen_clone_1");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['X-Appery-Database-Id'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': '{database_id}'
        }]
    });

    datasources.push(restservice1_clone_1);

    /*
     * Events and handlers
     */

    // Before Show
    var startScreen_clone_1_beforeshow = function() {
            Appery.CurrentScreen = "startScreen_clone_1";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var startScreen_clone_1_onLoad = function() {
            startScreen_clone_1_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            startScreen_clone_1_deviceEvents();
            startScreen_clone_1_windowEvents();
            startScreen_clone_1_elementsEvents();
        };

    // screen window events
    var startScreen_clone_1_windowEvents = function() {

            $('#startScreen_clone_1').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });
            $('#startScreen_clone_1').on({
                pageshow: function() {
                    try {
                        restservice1_clone_1.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                },
            });

        };

    // device events
    var startScreen_clone_1_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var startScreen_clone_1_elementsExtraJS = function() {
            // screen (startScreen_clone_1) extra code

            Appery.registerYoutubeComponent("startScreen_clone_1_adhd_spanish");

            Appery.registerYoutubeComponent("startScreen_clone_1_antidepressants_sp");

            Appery.registerYoutubeComponent("startScreen_clone_1_dep_sp");

            Appery.registerYoutubeComponent("startScreen_clone_1_DB_sp");

            Appery.registerYoutubeComponent("startScreen_clone_1_ED_sp");

            Appery.registerYoutubeComponent("startScreen_clone_1_infant");

            Appery.registerYoutubeComponent("startScreen_clone_1_panic");

            Appery.registerYoutubeComponent("startScreen_clone_1_sleep_sp");

            Appery.registerYoutubeComponent("startScreen_clone_1_weight");

        };

    // screen elements handler
    var startScreen_clone_1_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#startScreen_clone_1_mobileheader1 [name="mobilebutton_89"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('startScreen', {
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_clone_1_mobileheader1 [name="mobilebutton_89"]');
            $(document).off("click", '#startScreen_clone_1_mobileheader1 [name="mobilebutton_90"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Appery.navigateTo('tests', {
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_clone_1_mobileheader1 [name="mobilebutton_90"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="adhd_sp_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_adhd_spanish', 'mob', 'true');
                        toggle('startScreen_clone_1_adhd_sp_but_off', 'mob', 'false');
                        toggle('startScreen_clone_1_adhd_sp_but_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="adhd_sp_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="adhd_sp_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_adhd_sp_but_on', 'mob', 'false');
                        toggle('startScreen_clone_1_adhd_spanish', 'mob', 'false');
                        toggle('startScreen_clone_1_adhd_sp_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="adhd_sp_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="anti_sp_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_antidepressants_sp', 'mob', 'true');
                        toggle('startScreen_clone_1_anti_sp_but_on', 'mob', 'true');
                        toggle('startScreen_clone_1_anti_sp_but_off', 'mob', 'false');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="anti_sp_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="anti_sp_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_anti_sp_but_off', 'mob', 'true');
                        toggle('startScreen_clone_1_anti_sp_but_on', 'mob', 'false');
                        toggle('startScreen_clone_1_antidepressants_sp', 'mob', 'false');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="anti_sp_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="dep_sp_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_dep_sp', 'mob', 'true');
                        toggle('startScreen_clone_1_dep_sp_but_off', 'mob', 'false');
                        toggle('startScreen_clone_1_dep_sp_but_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="dep_sp_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="dep_sp_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_dep_sp', 'mob', 'false');
                        toggle('startScreen_clone_1_dep_sp_but_on', 'mob', 'false');
                        toggle('startScreen_clone_1_dep_sp_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="dep_sp_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="db_sp_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_db_sp_off', 'mob', 'false');
                        toggle('startScreen_clone_1_db_sp_on', 'mob', 'true');
                        toggle('startScreen_clone_1_DB_sp', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="db_sp_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="db_sp_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_db_sp_off', 'mob', 'true');
                        toggle('startScreen_clone_1_DB_sp', 'mob', 'false');
                        toggle('startScreen_clone_1_db_sp_on', 'mob', 'false');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="db_sp_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="ed_sp_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_ED_sp', 'mob', 'true');
                        toggle('startScreen_clone_1_ed_sp_but_off', 'mob', 'false');
                        toggle('startScreen_clone_1_ed_sp_but_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="ed_sp_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="ed_sp_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_ed_sp_but_off', 'mob', 'true');
                        toggle('startScreen_clone_1_ED_sp', 'mob', 'false');
                        toggle('startScreen_clone_1_ed_sp_but_on', 'mob', 'false');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="ed_sp_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="infant_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_infant', 'mob', 'true');
                        toggle('startScreen_clone_1_infant_but_off', 'mob', 'false');
                        toggle('startScreen_clone_1_infant_but_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="infant_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="infant_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_infant', 'mob', 'false');
                        toggle('startScreen_clone_1_infant_but_on', 'mob', 'false');
                        toggle('startScreen_clone_1_infant_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="infant_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="panic_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_panic_but_off', 'mob', 'false');
                        toggle('startScreen_clone_1_panic_but_on', 'mob', 'true');
                        toggle('startScreen_clone_1_panic', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="panic_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="panic_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_panic', 'mob', 'false');
                        toggle('startScreen_clone_1_panic_but_on', 'mob', 'false');
                        toggle('startScreen_clone_1_panic_but_off', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="panic_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="sleep_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_sleep_but_off', 'mob', 'false');
                        toggle('startScreen_clone_1_sleep_sp', 'mob', 'true');
                        toggle('startScreen_clone_1_sleep_but_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="sleep_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="sleep_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_sleep_but_off', 'mob', 'true');
                        toggle('startScreen_clone_1_sleep_sp', 'mob', 'false');
                        toggle('startScreen_clone_1_sleep_but_on', 'mob', 'false');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="sleep_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="weight_but_off"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_weight', 'mob', 'true');
                        toggle('startScreen_clone_1_weight_but_off', 'mob', 'false');
                        toggle('startScreen_clone_1_weight_but_on', 'mob', 'true');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="weight_but_off"]');
            $(document).off("click", '#startScreen_clone_1_mobilecontainer1 [name="weight_but_on"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        toggle('startScreen_clone_1_weight', 'mob', 'false');
                        toggle('startScreen_clone_1_weight_but_off', 'mob', 'true');
                        toggle('startScreen_clone_1_weight_but_on', 'mob', 'false');

                    }
                },
            }, '#startScreen_clone_1_mobilecontainer1 [name="weight_but_on"]');

            $(document).off("click", '#startScreen_clone_1_mobilefooter1 [name="mobilebutton_31"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        window.open('http://www.primarycareshrink.com', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                    }
                },
            }, '#startScreen_clone_1_mobilefooter1 [name="mobilebutton_31"]');

        };

    $(document).off("pagebeforeshow", "#startScreen_clone_1").on("pagebeforeshow", "#startScreen_clone_1", function(event, ui) {
        startScreen_clone_1_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_clone_1_beforeshow();
    } else {
        startScreen_clone_1_onLoad();
    }
};

$(document).off("pagecreate", "#startScreen_clone_1").on("pagecreate", "#startScreen_clone_1", function(event, ui) {
    Appery.processSelectMenu($(this));
    startScreen_clone_1_js();
});